services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: holidayvibez
      POSTGRES_PASSWORD: holidayvibez
      POSTGRES_DB: holiday_vibez_crm
    ports:
      - '5432:5432'
    volumes:
      - hv_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

volumes:
  hv_postgres_data:
